### ISSUE TITLE
[REGRESSION] Implicit Tiling Repeating request

### ISSUE THREAD

**Issue by AnthonyGlt** [NASA-AMMOS/3DTilesRendererJS#761] opened 2024-09-25 07:53 UTC
**Description**

Not exactly the same as https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/728
I've noticed that after moving the camera around, we start doing the same requests again and again, infinitely.

Could be link to the latest changes concerning the cache management, WDYT ?

**To Reproduce**

1. Load the tileset from https://github.com/AnthonyGlt/data/tree/main/arbres_rieux_glb
2. Rotate / Move the camera around
3. Check the network request

[Screencast from 23-09-2024 17:59:56.webm](https://github.com/user-attachments/assets/adc05089-b3fc-403f-937c-5fd184d9e2c3)

**Comment by gkjohnson** [comment] 2024-09-25 09:06
Thanks - I think it's due to this section:

https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/25790f4458d4e416daa44a8f809c5bd502aa4d81/src/base/TilesRendererBase.js#L740-L750

Which will unload a newly loaded tile if it turns out the memory used by tiles recently loaded in parallel have already pushed the cache over the threshold. The issue is that sometimes the tiles are marked as taking _no_ memory (tile subtrees) are being unnecessarily unloaded since they won't push the memory cache any further. And tiles that have had memory requirements previously cached (and therefore already accounted for) are being unloaded even though they're contributing to the fullness factor already. So we wind up in a loop where tiles are loaded, the cache is full, the tile that caused it to be full is unloaded, causing the cache to be unfull, and a new load is started. 

The following should fix it and hopefully be robust:
- Don't perform the check if tiles are marked as using _no_ memory and just keep them in the cache.
- Check if the tile memory is "unknown" by the LRUCache and the tile is therefore unaccounted for in the "fullness" before deciding to evict the tile after load.

This memory cache has turned out to be complicated - but I think it's a good feature to have. Thanks for reporting.

**Comment by AnthonyGlt** [comment] 2024-09-25 09:17
Thank you for the explanation !
It's very interesting to understand what is happening under the hood :+1: 

What do you mean by 
> the tile memory is "unknown" by the LRUCache

Does it concern the newly loaded tiles ? Or like as you referred to it before, the subtrees which have _no memory_ ?

The cache management looks tricky but you're right, it is a good feature :)

**Comment by gkjohnson** [comment] 2024-09-25 09:37
> the tile memory is "unknown" by the LRUCache

We can only know how much memory a tile will take up once it has been loaded so when we start loading for the first time the final memory footprint it "unknown" (treated as 0) but we optimistically add it in into the cache anyway assuming it's not already full. Once the tile is loaded we estimate the bytes required [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/src/three/TilesRenderer.js#L785) and then we update the memory usage in the cache [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/25790f4458d4e416daa44a8f809c5bd502aa4d81/src/base/TilesRendererBase.js#L740-L750). Of course since multiple "unknown" tiles are loading at once then it's possible we overloaded the cache since we didn't know how much memory would required. In this case we dispose of a newly loaded tile if the cache was filled by other unknown-size tiles while it was being loaded.

If the tile is unloaded and loaded again then we can know ahead of time the memory required and account for it to avoid loading other tiles just to unload them.

> the subtrees which have no memory ?

The cache is more realistically measuring the GPU memory requirements. Of course the subtrees use CPU memoy but I think this is less sensitive. So they are just marked as "0" which should mean they're "free" as far as the memory requirements are concerned.

**Comment by gkjohnson** [comment] 2024-09-29 10:15
> Load the tileset from https://github.com/AnthonyGlt/data/tree/main/arbres_rieux_glb

You may know this, already, but it's worth mentioning that the tile geometry in this tile set are very large. Update to 14 mb per tile in some cases. This is going to cause data to load more slowly and fill up the cache very quickly. It's fortunate that it helped find this bug, though 😁

**Comment by AnthonyGlt** [comment] 2024-09-30 07:45
Yes I've noticed it. It's good for testing :)

**Comment by AnthonyGlt** [comment] 2024-09-30 08:15
Is that why the all the tiles don't load ? We stop loading once the cache is full I guess.
![Screenshot from 2024-09-30 10-13-51](https://github.com/user-attachments/assets/ef96fbfa-f4e0-4e54-a93c-08d40a27b787)

**Comment by gkjohnson** [comment] 2024-09-30 08:17
Yeah that's right - once the cache is full no more tiles will load.

**Comment by gkjohnson** [comment] 2024-09-30 08:41
You can also adjust the cache to allow for more memory usage, as well. Right now the max cap defaults to 0.4 GB or ~400MB which seemed reasonable for something like mobile devices in addition to whatever else needs to be rendered. If you know you'll have more headroom you can raise the cap.

And to be clear this won't always result in gaps in the tile set. The traversal algorithm will only render a set of child tiles if all children have been loaded when using the "REPLACE" refinement. In that case you'll just wind up with parent tiles that don't refine because the children won't load.

**Closed** 2024-09-30 08:42 UTC
Labels: bug
