### ISSUE TITLE
Dispose not working properly

### ISSUE THREAD

**Issue by abaldacci** [NASA-AMMOS/3DTilesRendererJS#244] opened 2022-03-24 17:01 UTC
Hi,

I have done some tests about using the dispose function to free up the memory used by the library.

I have a minimal (typescript) example in which I load a (large) photogrammetric dataset and press a button for disposing everything.

Depending on how  I interact with the model,  after calling dispose() and detaching from the scene, some resources appear to remain linked to ThreeJS.

In particular, memory appears to be released (check done using ThreeJS Stats) but renderer.info.memory.textures and renderer.info.memory.geometries have a count different from zero.

Is this a known issue? Any idea?

Thanks

**Comment by gkjohnson** [comment] 2022-03-25 18:49
> Depending on how I interact with the model, after calling dispose() and detaching from the scene, some resources appear to remain linked to ThreeJS.

Can you elaborate with some more detailed repro steps? What do you mean by "depending on how I interact with the model"?

**Comment by abaldacci** [comment] 2022-03-28 07:52
Yes, I mean depending on how much I zoom on the model and thus on how much tiles are loaded.

If the model is viewed from a distance with few tiles are loaded  (for example from 2 to 20), the dispose function seems to work correctly.

As soon as I start zooming and lots of tiles are loaded, there is the problem described above.

Are  both active and non active tiles disposed  automatically or one should call markAllUnused() before the dipose call?

**Comment by gkjohnson** [comment] 2022-03-28 17:43
It seems there may be an issue related to calling "dispose" before removing the tile set from the scene or while geometry is downloading. It's not immediately clear to me where the issue is. Would you like to investigate and make a PR?

**Comment by abaldacci** [comment] 2022-03-28 19:43
Ok, I can take a look.

**Comment by gkjohnson** [comment] 2022-03-28 22:14
Great thanks! Let me know if you have any trouble or questions and I can point you in the right direction.

**Comment by gkjohnson** [comment] 2022-07-04 16:56
I just made a small fix for disposal in #272 but I don't think it's related to what you're seeing. The demos show the texture and geometry count in three.js after dispose is called and they all go to 0 on dispose / rebuild. I'll need more of a repro to look into this any more.

**Comment by kingwangwang** [comment] 2022-09-16 01:46
**### Why does loading the simplest model cause such errors? How can I solve them?**
![2022-09-16_093201](https://user-images.github
[1.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/9579977/1.zip)
usercontent.com/61161658/190538560-3c13a302-41a5-4198-950a-0cb131401214.png)
![2022-09-16_094040](https://user-images.githubusercontent.com/61161658/190538561-b1f0c26a-a68d-42c5-bef3-d41a52fba2f5.png)

**Comment by abaldacci** [comment] 2023-01-12 08:52
Sorry for the late reply. I will test again with a more recent version of the library.

Thanks

AB

**Comment by kingwangwang** [comment] 2023-01-12 08:52
您好！您的邮件已收到。我将在假期结束后，尽快给你回复。
祝您生活愉快。
BY WJC

**Comment by gkjohnson** [comment] 2023-01-12 09:43
Great, thanks! There was a suggested fix for dispose in #289 for the case where recursive tilesets were but it never got completed and tested properly. You can see my recommended change [here](https://github.com/NASA-AMMOS/3DTilesRendererJS/pull/289#issuecomment-1261016997) if you'd like to give that a try and test it out.

**Comment by gkjohnson** [comment] 2023-06-01 05:31
Fixed with #344

**Comment by kingwangwang** [comment] 2023-06-01 05:31
您好！您的邮件已收到。我将在假期结束后，尽快给你回复。祝您生活愉快。BY WJC

**Closed by gkjohnson** 2023-06-01 05:31 UTC
Labels: bug
