### ISSUE TITLE
Some b3dms which use other encoding methods cann't load

### ISSUE THREAD

**Issue by 2226174644** [NASA-AMMOS/3DTilesRendererJS#229] opened 2021-11-30 11:51 UTC
When I used B3DMLoader to load my b3dms, it didn't work and log:
![image](https://user-images.githubusercontent.com/51537408/144041251-c3bc5ff7-f9be-422f-864c-c8f5cb862d6e.png)
from
![image](https://user-images.githubusercontent.com/51537408/144041398-613a38f7-9acb-41db-b698-09326ce12d04.png)
I think the reason is from encoding methods ,because I compared my b3dms with other example b3dms in txt ,they are different.
![image](https://user-images.githubusercontent.com/51537408/144041934-efb961b6-8e20-47e3-b9f0-d86cbfe02475.png)
(left is mine ,right is a example).

And I have tested , my 3DTiles which contains the b3dms can run in Cesium.
I need your help .

**Comment by gkjohnson** [comment] 2021-11-30 16:44
Hello! I have not had to deal with this before but are you sure the content is loading correctly in the network tab? What are the magic bytes and other values being read as? Can you supply a b3dm for testing to reproduce the issue.

Unfortunately my time is limited so I would appreciate some help digging into the issue further. You can use the [b3dmExample](https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/master/example/b3dmExample.js) page to simplify the debugging process.

**Comment by 2226174644** [comment] 2021-12-01 02:43
Sorry,It's my fault. I used wrong url to cause this error.
But it still cann't  be loaded,because its source image could not be decoded.
![image](https://user-images.githubusercontent.com/51537408/144162030-f5b7a789-96d7-49c2-8687-aebdc1e42d2c.png)
And in network tab, it's likely ok.
![image](https://user-images.githubusercontent.com/51537408/144162264-65239b99-c844-46fd-86c9-762448d9c3da.png)

Here is my data.
[Data.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/7630358/Data.zip)

**Comment by gkjohnson** [comment] 2021-12-01 07:52
Is you're server not configured to return 404 error codes? If the URL was wrong the network tab and console should be showing errors. The images that cannot be decoded should also be showing error codes, as well.

There does seem to be small bug in the B3DM (and other) loader implementation, though. Specifically it's not setting the working path correctly because it's not splitting the file path on slashes correctly, which I don't think should be a difficult fix.

**Comment by gkjohnson** [comment] 2022-01-06 18:40
Just merged with #230. I'll publish later today or tomorrow!

**Closed** 2022-01-06 18:43 UTC
Labels: bug

**Comment by gkjohnson** [comment] 2022-01-07 05:35
Published in v0.3.5
