### ISSUE TITLE
won't load properly on 3DTilesRendererJS

### ISSUE THREAD

**Issue by yoyomule** [NASA-AMMOS/3DTilesRendererJS#78] opened 2020-06-22 08:46 UTC
Hello, I converted the bim model to 3dtile, which can be loaded normally in cesium. But it won't load properly on 3DTilesRendererJS. The error is as follows pic, it seems to be missing a file with root.b3dm
![image](https://user-images.githubusercontent.com/10000818/85267344-bc4e2f00-b4a7-11ea-81ed-78b6885d0bd6.png)
![image](https://user-images.githubusercontent.com/10000818/85267364-c1ab7980-b4a7-11ea-8ba6-cd141703c4f4.png)
 I provided the test file in the attachment.
[bim3dtile.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/4811490/bim3dtile.zip)

**Comment by gkjohnson** [comment] 2020-06-22 17:24
Hi @yoyomule! Thanks for the report.

I downloaded the zip you provided and I'm able to load the tileset without errors. Can you provide more information on your set up? Would you also be able to provide a screenshot of what you expect it to look like?

Please also keep in mind that there are still some unimplemented features such as CMPT file format that can't currently be loaded in this tileset, as well. See #15 for more details.

**Comment by gkjohnson** [comment] 2020-06-30 04:11
Ping @yoyomule. Is this still an issue? I'm not seeing the problems you've reported.

**Comment by yoyomule** [comment] 2020-06-30 04:14
Sorry, this question is here
https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/78#issuecomment-647668347

Garrett Johnson <notifications@github.com> 于2020年6月30日周二 下午12:11写道：

**Comment by gkjohnson** [comment] 2020-06-30 04:51
> Sorry, this question is here

Yes and I've responded here: https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/78#issuecomment-647668347.

I cannot reproduce your problem.

**Comment by yoyomule** [comment] 2020-06-30 05:56
Hello, we loaded it, but it is not displayed correctly. I provided two pictures, one is loaded in cesium, and the other is loaded in 3DTilesRendererJS. As you can see, the situation in 3DTilesRendererJS is wrong, and related error messages are also prompted. 
![image](https://user-images.githubusercontent.com/10000818/86088606-3ea6a680-bad9-11ea-8641-0c3bfddc4afa.png)
![image](https://user-images.githubusercontent.com/10000818/86088614-41a19700-bad9-11ea-96b8-94cbf8883f37.png)
[bim3dtile.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/4849703/bim3dtile.zip)

**Comment by gkjohnson** [comment] 2020-07-01 04:44
@yoyomule 

Great that looks more like what I was seeing.

I have tried loading the `/0/2/b0.b3md` file alone and scaled it down and saw this:

![image](https://user-images.githubusercontent.com/734200/86203311-9107b780-bb19-11ea-893a-777e6d1606da.png)

I saved it out as a GLB file and ran it through [this GTLF Validator](https://github.khronos.org/glTF-Validator/) and it looks like there are a lot of validation errors on the file. One that sticks out is that a `WEB3D_quantized_attributes` extension is used but is not recognized. According to the [GLTF Spec](https://github.com/KhronosGroup/glTF/blob/master/extensions/README.md) this extension is intended for use with GLTF 1.0 only, so it seems that the B3DM file is being incorrectly generated. There are other invalid fields in the GLTF, as well, which explains why the render does not look correct. It seems that Cesium is tolerant to these invalid files in a way that three.js is not.

Unfortunately without valid files I can't do a lot to help with this. How did you generate this 3D Tiles dataset? I recommend looking into why the generation process produced files with incorrect extensions.

Here is the converted GLB in case you want to run the file through the validator yourself to see the errors:

[b0.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/4855716/b0.zip)

**Comment by yoyomule** [comment] 2020-07-03 01:50
As far as we know, b3dm does not necessarily fully follow the gltf standard, it does a compatible treatment. This is the revit model we convert, which contains both the model and the property information corresponding to the model. In addition, we have enabled quantum compression (the bim model is more advantageous with quantum compression), so this compatibility(WEB3D_quantized_attributes) tip appears. At the same time, we provide another scenario transformation model without enabling quantum compression.
[bim3dtile2.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/4867324/bim3dtile2.zip)

**Comment by gkjohnson** [comment] 2020-07-03 03:48
> As far as we know, b3dm does not necessarily fully follow the gltf standard

The documentation for the B3DM file format very specifically states [that the embedded mesh is of the GLTF 2.0 format](https://github.com/CesiumGS/3d-tiles/tree/master/specification/TileFormats/Batched3DModel#binary-gltf). It's possible that Cesium implements a more flexible interpretation of the spec that supports both GLTF 1.0 and 2.0, which could be why it works there but it's outside the scope of what the spec says is valid. The B3DMLoader in this package depends on the GTLFLoader in the official three.js library so ultimately whatever they support is what will work here.

I've made a few changes to the renderer to handle some failure cases that weren't accounted for previously (and hacked in Draco decompression, see #28) and here's what I'm able to load now. It looks like some of the bounding box positions are off but we can track that down after the data set is working more completely -- thanks for the extra data to test with! It's helped with a couple unsupported cases so far.

![image](https://user-images.githubusercontent.com/734200/86429268-ebcd1a80-bca3-11ea-8b13-c09631436e64.png)

I'm still getting errors on loading 4 of the GLTF blobs, though, one of which I'll attach below. Running it through this [gltf viewer](https://gltf-viewer.donmccurdy.com/) it looks like an embedded texture is failing to load. And running it through the [validator](https://github.khronos.org/glTF-Validator/) it looks like there are quite a few other issues, as well.

Here's the glb that's failing embedded in the `./1/0/0.b3dm` file:

[failed-bim.zip](https://github.com/NASA-AMMOS/3DTilesRendererJS/files/4867642/failed-bim.zip)

**Comment by gkjohnson** [comment] 2020-07-22 03:53
Ping @yoyomule.

With #105 now merged the example now supports DRACO decompression and I've added instructions on how to add it [here](https://github.com/NASA-AMMOS/3DTilesRendererJS#adding-draco-decompression-support). It looks like the files you provided are using is using and `image/crn` format, as well, which seems to be from [crunch](https://github.com/BinomialLLC/crunch) but it's not supported by three.js' GLTFLoader. For that I recommend making an issue asking for support in the [official three.js project](https://github.com/mrdoob/three.js) or using another supported compressed image format like KTX2 or DDS.

I think I've done all I can for the moment. I think the GLTF validation errors need to be worked out before we can consider any of the other issues here a bug. Let me know if you get any of those figured out and I'm happy to try out a new tileset.

**Comment by yoyomule** [comment] 2020-08-18 03:08
模型.3dtilezip
<https://drive.google.com/file/d/1B4P3D5awALhueatDz79aHanEL_jSKT4i/view?usp=drive_web>
Thank you for your reply. I re-uploaded a 3dtile file. The data of this
file is larger. There are still many errors in our loading. I hope this
file is useful for your development. PS. In cesium, this file is normal.

Garrett Johnson <notifications@github.com> 于2020年7月22日周三 上午11:53写道：

**Comment by gkjohnson** [comment] 2020-08-18 03:30
Great thanks @yoyomule! Unfortunately I can't download the zip, though. Can you make it public or give access to `garrett.kjohnson@gmail.com`?

**Comment by gkjohnson** [comment] 2020-08-18 15:11
Thanks for the new data set @yoyomule! This tile set seems to have the same issues mentioned above (https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/78#issuecomment-652186806) in that it contains GLTF blobs that do not adhere to the GLTF spec -- specifically it at least uses the `WEB3D_quantized_attributes` extensions which is not a part of the GLTF spec.

> PS. In cesium, this file is normal.

Cesium seems to support functionality that is outside of the GLTF spec and their own B3DM and 3DTiles spec. Unfortunately including undocumented features is outside the scope of this project. If you want to use this project you'll have to generate valid B3DM files that adhere to the [B3DM Spec](https://github.com/CesiumGS/3d-tiles/tree/master/specification/TileFormats/Batched3DModel) and embed valid GLTF 2.0 data, which the ones you've provided do not.

**Comment by gkjohnson** [comment] 2020-10-09 22:50
I'm gonna go ahead and close this -- if you have other thoughts on the issue or have a tileset you feel addresses the above comments do feel free to open a new one!

**Closed by gkjohnson** 2020-10-09 22:50 UTC

**Comment by gkjohnson** [comment] 2021-01-19 15:59
I just fixed an issue that caused incorrect transformations in #151, which likely caused the incorrect transformations here. It doesn't address the quantized attributes but the positions of correctly loaded models should be correct, now. It's been released in v0.2.5.
