### ISSUE TITLE
Could not load b3dm version 0.0 ,

### ISSUE THREAD

**Issue by MrYang614** [NASA-AMMOS/3DTilesRendererJS#572] opened 2024-06-03 07:13 UTC
Cannot load file for b3dm version 0.0, with error reported. If only support loading the version 1.0 files, then I will try to get the version 1.0 files.

**Comment by gkjohnson** [comment] 2024-06-03 08:26
If you don't share the file or the error then nothing specific can be answered. It sounds like a duplicate of https://github.com/NASA-AMMOS/3DTilesRendererJS/issues/508, though, meaning it is not supported.

**Comment by MrYang614** [comment] 2024-06-03 08:37
here ！ Very strange error, can not find the cause of the error, located in html, currently I can only find one different from the 3dtiles version
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/107246452/bf7bd6c6-782c-4fa7-8bf4-129474af476c)
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/107246452/61ad494c-138d-4780-905a-4a7e6c15159b)
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/107246452/c6830556-2601-4a1f-836b-658082deeecb)

**Comment by MrYang614** [comment] 2024-06-03 08:38
all code
```
import * as THREE from "three";
import { TilesRenderer } from "3d-tiles-renderer";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import Stats from 'three/examples/jsm/libs/stats.module'
import { DRACOLoader } from "three/examples/jsm/loaders/DRACOLoader.js";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader.js";
import { Line2 } from "three/examples/jsm/lines/Line2.js";
import { LineGeometry } from "three/examples/jsm/lines/LineGeometry.js";
import { LineMaterial } from "three/examples/jsm/lines/LineMaterial.js";


const material = new LineMaterial({ color: 0xfff000, depthTest: false, transparent: true, linewidth: 5, resolution: new THREE.Vector2(window.innerWidth, window.innerHeight) })

const { innerWidth, innerHeight } = window;
const aspect = innerWidth / innerHeight;

const renderer = new THREE.WebGLRenderer({
  antialias: true,
  logarithmicDepthBuffer: true,
});
renderer.setPixelRatio(window.devicePixelRatio);
renderer.setSize(innerWidth, innerHeight);
renderer.setAnimationLoop(animate.bind(this));
document.body.appendChild(renderer.domElement);

const camera = new THREE.PerspectiveCamera(60, aspect, 0.01, 100000);
camera.position.set(0, 100, 100)

const scene = new THREE.Scene();

const controls = new OrbitControls(camera, renderer.domElement);


const axes = new THREE.AxesHelper(100);
axes.material.depthTest = false
axes.material.transparent = true
scene.add(axes);

const light = new THREE.AmbientLight(0xffffff, 0.5);
scene.add(light);

const stat = new Stats()
document.body.appendChild(stat.dom)

const rayIntersect = new THREE.Group();

const rayIntersectMat = new THREE.MeshBasicMaterial({ color: 0xe91e63 });
const rayMesh = new THREE.Mesh(new THREE.CylinderGeometry(0.25, 0.25, 6), rayIntersectMat);
rayMesh.rotation.x = Math.PI / 2;
rayMesh.position.z += 3;
rayIntersect.add(rayMesh);

const rayRing = new THREE.Mesh(new THREE.TorusGeometry(1.5, 0.2, 16, 100), rayIntersectMat);
rayIntersect.add(rayRing);
scene.add(rayIntersect);
rayIntersect.visible = false;

const path = './terra_b3dms/tileset.json'
const tilesRenderer = new TilesRenderer(path)
tilesRenderer.optimizeRaycast = true
tilesRenderer.loadSiblings = false
tilesRenderer.group.raycast.firstHitOnly = true

const dracoLoader = new DRACOLoader();
dracoLoader.setDecoderPath("./draco/draco");

const loader = new GLTFLoader(tilesRenderer.manager);
loader.setDRACOLoader(dracoLoader);

tilesRenderer.manager.addHandler(/\.gltf$/, loader);

function addLineToWorld(position) {
  const lineGeometry = new LineGeometry().setPositions(position)
  const line = new Line2(lineGeometry, material)
  scene.add(line)
  return line
}

let first = true
tilesRenderer.onLoadTileSet = async (tileSet) => {

  if (first) {

    const up = await getUpFromTileset(path)

    console.log(up);

    // 由于 3d-tiles 导出文件的坐标系和 three 的标准坐标系，在 Y 和 Z 的轴向上是相反的（ Y=>Z   Z=>Y ）
    // 以及，导出的模型 position 默认定位在球面上，需要将模型处理到 （0,0,0） ,并且旋转至建筑的北方 对应 （0,0,-1）
    // 所以做如下计算
    const matrix = computeTransformMatrix(tilesRenderer, new THREE.Vector3(0, -20, 0), up)
    // 对模型执行矩阵变换。
    tilesRenderer.group.applyMatrix4(matrix)

    // 获取模型的几何中心。
    // const center = new THREE.Vector3()
    // const box = new THREE.Box3()
    // tilesRenderer.getBounds(box)
    // box.getCenter(center)
    // center.applyMatrix4(matrix)

    // axes.position.copy(center)
    // controls.target.copy(center)
    // camera.position.copy(center)
    // camera.position.add(new THREE.Vector3(100, 100, 100))

    first = false

  }

}

tilesRenderer.onLoadModel = scene => {
  scene.traverse(child => {
    if (child.material) {

      // child.originalMaterial = child.material;

      /** @type {THREE.Material} */
      const material = child.material
      const modelMatrix = child.matrixWorld


      material.onBeforeCompile = shader => {
        shader.uniforms.mm = { value: modelMatrix }
        shader.vertexShader = shader.vertexShader.replace(`#include <common>`,
          `#include <common>
            uniform mat4 mm;
            varying vec3 vmPosition;
          `
        )
        shader.vertexShader = shader.vertexShader.replace(`#include <project_vertex>`,
          `#include <project_vertex>
          vmPosition = (mm * vec4(transformed,1.) ).xyz ;
        `
        )
        shader.fragmentShader = shader.fragmentShader.replace(`#include <common>`,
          `#include <common>
          varying vec3 vmPosition;
        `
        )
        shader.fragmentShader = shader.fragmentShader.replace(`#include <clipping_planes_fragment>`,
          `#include <clipping_planes_fragment>
              if( distance(vmPosition,vec3( 2.3283064365386963e-10,  6366904.248835246,  -241698.85331815295)) < 100.) discard;
            `
        )
      }
    }
  })

}

tilesRenderer.setCamera(camera);
tilesRenderer.setResolutionFromRenderer(camera, renderer);

scene.add(tilesRenderer.group)

const raycaster = new THREE.Raycaster()
raycaster.firstHitOnly = true
const mouse = new THREE.Vector2()
document.body.addEventListener("mousemove", e => {

  const bounds = renderer.domElement.getBoundingClientRect();
  mouse.x = e.clientX - bounds.x;
  mouse.y = e.clientY - bounds.y;
  mouse.x = (mouse.x / bounds.width) * 2 - 1;
  mouse.y = - (mouse.y / bounds.height) * 2 + 1;
  raycaster.setFromCamera(mouse, camera)
  const result = raycaster.intersectObject(tilesRenderer.group, true)
  if (result.length) {
    const hit = result[0]
    const point = hit.point
    rayIntersect.position.copy(point);

    console.log(point);

    const face = hit.face
    const normal = face.normal
    normal.transformDirection(hit.object.matrixWorld)
    rayIntersect.lookAt(
      point.x + normal.x,
      point.y + normal.y,
      point.z + normal.z
    );
    rayIntersect.visible = true;
  } else {
    rayIntersect.visible = false;
  }
})

function animate() {
  tilesRenderer.update()
  controls.update();
  stat.update()

  renderer.render(scene, camera);
}

animate()


/**
 * 根据 3dtiles 文件加载而来的模型，位置在地球球面上，需要转换至 three 坐标系中的原点。再计算正确的北面向量，将模型旋转至正确方向。
 * @param {TilesRenderer} tilesRenderer 
 * @param {THREE.Vector3} orientation 定位原点，默认 0,0,0 ; 首次变换结束后，再根据实际情况设置此值。
 * @param {THREE.Vector3} defaultUp  默认 up 方向为 0,0,1 ; 在 3dtiles 中 Y 对应 three 坐标系的 Z ,所以，取 Y 不是 0,1,0 是 0,0,1 
 * @returns 
 */
function computeTransformMatrix(tilesRenderer, orientation = new THREE.Vector3(), defaultUp = new THREE.Vector3(0, 0, 1)) {
  // 获取模型的几何中心。
  const center = new THREE.Vector3()
  const box = new THREE.Box3()
  tilesRenderer.getBounds(box)
  box.getCenter(center)

  // 克隆初始 center ，计算 north normal 
  const centerClone = center.clone()

  // 修正倾斜的坐标系。
  const rotationX = - Math.atan(center.z / center.y)

  // 旋转X轴，将坐标Z轴分量归零。
  const matrix4_rx = new THREE.Matrix4().makeRotationX(rotationX)
  center.applyMatrix4(matrix4_rx)

  // 旋转Z轴，将坐标X轴分量归零。
  const rotationZ = Math.atan(center.x / center.y)
  const matrix4_rz = new THREE.Matrix4().makeRotationZ(rotationZ)
  center.applyMatrix4(matrix4_rz)

  // 此时模型处于北极极点位置，(0,6371542.289833925,0)， 需要将其归零。
  const matrix_t = new THREE.Matrix4().makeTranslation(center.clone().negate())
  center.applyMatrix4(matrix_t)

  const matrix = new THREE.Matrix4().premultiply(matrix4_rx).premultiply(matrix4_rz).premultiply(matrix_t)

  // 计算北方向
  const v1 = new THREE.Vector3().crossVectors(defaultUp, centerClone)
  const v2 = new THREE.Vector3().crossVectors(centerClone, v1)

  // 计算北方向在原点的数据
  const p1 = centerClone.applyMatrix4(matrix)
  const p2 = centerClone.clone().add(v2).applyMatrix4(matrix)

  // 计算需要旋转的角度，将北面旋转至 (0,0,-1) ，写出旋转矩阵
  const angle = getSignedAngleBetweenVectors(new THREE.Vector3(0, 0, -1), p2)
  const matrix_r2 = new THREE.Matrix4().makeRotationY(-angle)

  // 将变换矩阵乘以旋转矩阵
  matrix.premultiply(matrix_r2)

  // 确定定位原点，写出平移矩阵
  const matrix_t_2 = new THREE.Matrix4().makeTranslation(orientation.negate())
  matrix.premultiply(matrix_t_2)

  return matrix
}


/** 计算两个向量之间的夹角,点积计算投影，如果误差在 dotThreshold 之内，判定两个向量同方向，向量之间的夹角为 0  */
export function getAngleBetweenVectors(v1, v2, dotThreshold = 0.0005) {

  v1 = v1.clone().normalize()
  v2 = v2.clone().normalize()

  let angle = 0;
  const dot = v1.dot(v2);

  if (dot > 1 - dotThreshold) {
    angle = 0;
  } else if (dot < dotThreshold - 1) {
    angle = Math.PI;
  } else {
    angle = Math.acos(dot);
  }

  return angle;

}

/** 返回两个向量之间的有符号的夹角，首先计算无符号夹角数值，再根据两个向量的叉积计算出两个向量所在平面的法线的方向，将这个结果与基准法线 normal 进行点积运算，判定符号 */
export function getSignedAngleBetweenVectors(v1, v2, normal = new THREE.Vector3(0, 1, 0), dotThreshold = 0.0005) {

  v1 = v1.clone().normalize()
  v2 = v2.clone().normalize()

  let angle = getAngleBetweenVectors(v1, v2, dotThreshold);

  const cross = new THREE.Vector3().crossVectors(v1, v2);

  if (normal.dot(cross) < 0) angle = -angle;

  return angle;

}


async function getUpFromTileset(url) {

  const res = await fetch(url)
  const obj = JSON.parse(await res.text())

  const gltfUpAxis = obj.asset.gltfUpAxis

  switch (gltfUpAxis) {
    case "X":
      return new THREE.Vector3(1, 0, 0)
    case "Y":
      return new THREE.Vector3(0, 0, 1)
    case "Z":
      return new THREE.Vector3(0, 1, 0)
    default:
      return new THREE.Vector3(0, 1, 0)
  }

}

```

**Comment by MrYang614** [comment] 2024-06-03 09:15
> If you don't share the file or the error then nothing specific can be answered. It sounds like a duplicate of #508, though, meaning it is not supported. It is recommended to use at least the 1.0 version of the 3d tiles specification.

here ！ Very strange error, can not find the cause of the error, located in html, currently I can only find two different from the 3dtiles, one is version , another is dracoLoader

![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/107246452/4561cb38-dcf4-4fc3-bc2d-979f12ed8f3a)
![image](https://github.com/NASA-AMMOS/3DTilesRendererJS/assets/107246452/2eaa034c-02b8-44b9-b7e1-ae09d3126111)

**Comment by MrYang614** [comment] 2024-06-03 09:17
> If you don't share the file or the error then nothing specific can be answered. It sounds like a duplicate of #508, though, meaning it is not supported. It is recommended to use at least the 1.0 version of the 3d tiles specification.

I try to load other 3dtiles with v1.0 , without dracoloader , it is no problem
```
const path = './Model_0/tileset.json'
const tilesRenderer = new TilesRenderer(path)
tilesRenderer.optimizeRaycast = true
tilesRenderer.loadSiblings = false
tilesRenderer.group.raycast.firstHitOnly = true

const dracoLoader = new DRACOLoader();
dracoLoader.setDecoderPath("./draco/draco");

const loader = new GLTFLoader(tilesRenderer.manager);
loader.setDRACOLoader(dracoLoader);

tilesRenderer.manager.addHandler(/\.gltf$/, loader);

```

**Comment by MrYang614** [comment] 2024-06-03 09:24
> 如果您不共享文件或错误，则无法回答任何具体问题。不过，这听起来像是 #508 的副本，这意味着它不受支持。建议至少使用 1.0 版本的 3d tiles 规范。

thanks , i will try to upgrade version for the problem

**Comment by gkjohnson** [comment] 2024-06-03 10:24
The draco loader issue looks unrelated to this project. I'd check the build settings to make sure the decoder files are being loaded correctly.

> thanks , i will try to upgrade version for the problem

Okay we'll close this for now, then

**Closed by gkjohnson** 2024-06-03 10:24 UTC
Labels: question
