### ISSUE TITLE
Loading 3D tiles from Cesium Ion，cause page jam、cpu 100%

### ISSUE THREAD

**Issue by WaterSeeding** [NASA-AMMOS/3DTilesRendererJS#269] opened 2022-06-29 09:09 UTC
When I load 3D tiles from cesium ion, whether I load a page written by myself or an official example for testing, there will be a lot of content loaded at one time. When the CPU runs to 100%, the page is directly stuck and cannot be operated, as shown in the following figure:

![1](https://user-images.githubusercontent.com/31184164/176398532-8b031527-8f8a-4aff-8ae9-13e917cb5dab.png)

![2](https://user-images.githubusercontent.com/31184164/176398560-9495d7a3-4f8f-4c0e-baec-e7f4abd5672d.png)

This is my code: 
![image](https://user-images.githubusercontent.com/31184164/176398725-e23369a8-aa0c-4c03-a485-63341f1409b8.png)

**Comment by WaterSeeding** [comment] 2022-06-29 09:11
![image](https://user-images.githubusercontent.com/31184164/176399266-1647ed9f-5984-44fb-b1ec-b0e20c1291d8.png)

**Comment by gkjohnson** [comment] 2022-06-29 16:38
You can see in the console that your tileset uses the "Region" datatype which is not currently supported (see #66). If you'd like to help add basic support for regions I'm happy to provide guidance.

**Comment by WaterSeeding** [comment] 2022-06-30 03:28
> You can see in the console that your tileset uses the "Region" datatype which is not currently supported (see #66). If you'd like to help add basic support for regions I'm happy to provide guidance.

Yes, I want to use this function. Please give me some help

**Comment by gkjohnson** [comment] 2022-07-04 17:43
I'll close this a duplicate of #66 for now. Let me know if you have other questions about adding support.

**Closed by gkjohnson** 2022-07-04 17:43 UTC
Labels: question

**Comment by WaterSeeding** [comment] 2022-08-08 08:49
> A region bounding volume is defined here:
> 
> https://github.com/CesiumGS/3d-tiles/tree/main/specification#region
> 
> It's a patch defined by a latitude, longitude, and height delta on the WGS 84 ellipsoid. A simple approach to supporting a region volume is to generate a sphere from the region coordinates so that can be used for frustum culling etc. That could be added here:
> 
> https://github.com/NASA-AMMOS/3DTilesRendererJS/blob/3f02bcbc38bebfde4e74e99553f202275075cd12/src/three/TilesRenderer.js#L538-L543

Hello, excuse me

How can I generate a box from the region coordinates
![image](https://user-images.githubusercontent.com/31184164/183378519-95eb8437-6a43-4c7c-ab43-dbef84547318.png)

**Comment by gkjohnson** [comment] 2022-08-08 17:56
The region bounding volume is described in the specification here:

https://github.com/CesiumGS/3d-tiles/tree/main/specification#region

And there's source in the cesium renderer here for the region bounding volume:

https://github.com/CesiumGS/cesium/blob/main/Source/Scene/TileBoundingRegion.js

That should hopefully provide enough information to get started.

**Comment by WaterSeeding** [comment] 2022-08-09 07:22
> The region bounding volume is described in the specification here:
> 
> https://github.com/CesiumGS/3d-tiles/tree/main/specification#region
> 
> And there's source in the cesium renderer here for the region bounding volume:
> 
> https://github.com/CesiumGS/cesium/blob/main/Source/Scene/TileBoundingRegion.js
> 
> That should hopefully provide enough information to get started.

Thank you for your reply. I will try to have a look
