### ISSUE TITLE
"Render on change" example enhanchement

### ISSUE THREAD

**Issue by liberostelios** [NASA-AMMOS/3DTilesRendererJS#118] opened 2020-09-25 11:33 UTC
The current [example](https://github.com/NASA-AMMOS/3DTilesRendererJS#render-on-change) for not using a loop works, but it won't start loading the tiles unless something forces a second `tilesRenderer.update();` to be called.

This can be improved by making `needsRerender` an integer with the number of times to re-render and starting with 2. So the example would be:

```JavaScript
let needsRerender = 2;
const tilesRenderer = new TilesRenderer( './path/to/tileset.json' );
tilesRenderer.onLoadTileSet = () => needsRerender = 1;
tilesRenderer.onLoadModel = () => needsRerender = 1;

function renderLoop() {

	requestAnimationFrame( renderLoop );
	if ( needsRerender > 0) {
	
		needsRerender--;
		tilesRenderer.update();
		renderer.render( camera, scene );
	
	}

}
renderLoop();
```

There is also a typo on `upadate()`.

**Comment by gkjohnson** [comment] 2020-09-25 19:41
> There is also a typo on `upadate()`.

Heh, thanks :) fixed!

> The current example for not using a loop works, but it won't start loading the tiles unless something forces a second `tilesRenderer.update();` to be called.

Hmm I thought that's what #112 addressed? If this is true then I think it's a bug. Have you tracked down why? Is `onLoadTileSet` being fired? Here's what should be happening:

1. Initial update is called which  triggers load of tileset.json
1. tileset.json finishes loading which fires `onLoadTileSet` setting the render flag
1. update is called again with triggers load of tile geometry.
1. tile geometry finishes loading which fires `onLoadModel` setting the render flag
1. repeat

**Comment by liberostelios** [comment] 2020-09-25 20:01
>     2. tileset.json finishes loading which fires `onLoadTileSet` setting the render flag
> 
>     3. update is called again with triggers load of tile geometry.
> 
>     4. tile geometry finishes loading which fires `onLoadModel` setting the render flag

Actually, the example above was incorrect. This is the part that breaks. So the right code would be:

```JavaScript
let needsRerender = 1;
const tilesRenderer = new TilesRenderer( './path/to/tileset.json' );
tilesRenderer.onLoadTileSet = () => needsRerender = 2;
tilesRenderer.onLoadModel = () => needsRerender = 1;

function renderLoop() {

	requestAnimationFrame( renderLoop );
	if ( needsRerender > 0) {
	
		needsRerender--;
		tilesRenderer.update();
		renderer.render( camera, scene );
	
	}

}
renderLoop();
```

Well, #112 solves the issue in the sense that you can now initiate the two calls after the `tileset.json` is downloaded (which, if big enough, could take a while). For some reason, though, two `update()` calls are required after the tileset is downloaded in order to initiate the first tile geometry download. At least that's for me.

**Comment by gkjohnson** [comment] 2020-09-26 01:02
> For some reason, though, two update() calls are required after the tileset is downloaded in order to initiate the first tile geometry download.

Hm I'm unable reproduce this. Here are the changes I'd made with logs to show when tilesets and models are loaded and the terrain updates correctly. Note that manipulating orbit controls will not rerender with this quick change:

https://github.com/NASA-AMMOS/3DTilesRendererJS/compare/load-callback-repro

Do you mind modifying the example page to show the problem?

**Comment by liberostelios** [comment] 2020-09-26 09:43
That's interesting. We are using the library in project and we have to update twice. You can check the code here:

https://github.com/tudelft3d/3dbag-viewer/blob/feature/upgrade-3dtiles-lib/src/components/ThreeViewer.vue

Keep in mind, though, that this is using a fork which adds this modification:

https://github.com/liberostelios/3DTilesRendererJS/commit/91dbb3e14dc1c8699a21945ad4cb5b5a9cb4146f

This is to force error calculation on empty tiles, as we discussed in #111. Could this be the problem?

**Comment by gkjohnson** [comment] 2020-09-26 23:30
It's possible that the camera world matrix is not up date when `tiles.update` is called the first time because it's [updated here](https://github.com/tudelft3d/3dbag-viewer/blob/feature/upgrade-3dtiles-lib/src/components/ThreeViewer.vue#L307) rather than beforehand.

It's mentioned in the update docs that it needs to be updated beforehand but I've updated the example code so it's more clear. Let me know if that works!

**Comment by liberostelios** [comment] 2020-09-27 12:12
I've moved `camera.updateMatrixWorld()` before `tiles.update()` and still get the same behaviour. That's weird. I guess for now I'll leave it like that, known that it's probably that has to do with our specific setup.

**Comment by gkjohnson** [comment] 2020-09-27 22:46
Hm thats odd then 🤔 Without digging into the code further to debug I'm not sure if I can spot anything further. Would you be able to make a small repro with the example page? Maybe it's something to do with the particular tileset being used? Or maybe it is small change you've made?

**Comment by liberostelios** [comment] 2020-09-28 12:15
Interestingly, it is the change that I made. I just checked without it and in that case there is only one update call required.

I am not sure I can track down what that is, but maybe I should given #119.

**Comment by gkjohnson** [comment] 2020-10-09 22:47
I'm gonna go ahead and close this if you don't mind because I'm unable to reproduce the issue. If it turns out this is a problem that can be reproduced in the example code then lets reopen and we can track it down!

**Closed by gkjohnson** 2020-10-09 22:47 UTC

**Comment by liberostelios** [comment] 2020-10-10 17:06
That's a fair point. I don't think it's worth wasting more time on it.
